; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v2 on Thu Jan 17 2019 20:56:51 GMT+0100 (hora estándar de Europa central)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


