; resume.g
; called before a print from SD card is resumed
;
; generated by RepRapFirmware Configuration Tool v2 on Thu Jan 17 2019 20:56:52 GMT+0100 (hora estándar de Europa central)
M83                  ; relative extruder moves
G1 E10 F3600         ; extrude 9.8mm of filament
M291 S3 R"Filament Change" P"Remove filament purge from nozzle? then press OK"
G1 R1 X0 Y0 Z5 F6000 ; go to 5mm above position of the last print move
G1 R1 X0 Y0          ; go back to the last print move



