; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v2 on Thu Jan 17 2019 20:56:52 GMT+0100 (hora estándar de Europa central)

G91
G1 Z5 F3600
G90
G1 X0 Y220