; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v2 on Thu Jan 17 2019 20:56:52 GMT+0100 (hora estándar de Europa central)
; Wait for set temperatures to be reached
M116 P0

