; homez.g
; called to home the Z axis
;
; generated by RepRapFirmware Configuration Tool v2.0.4 on Thu Sep 26 2019 10:50:21 GMT+0200 (Central European Summer Time)
 G91               ; relative positioning
 G1 Z5 F6000 S2    ; lift Z relative to current position
 G90
 G1 X100 Y60 F600
 G30
 G91              ; relative positioning
 G1 Z5 F100 S2    ; lift Z relative to current position
 G90              ; absolute positioning
