; retractprobe.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v2.0.4 on Thu Sep 26 2019 10:50:21 GMT+0200 (Central European Summer Time)
; insert codes for retracting the Z probe here

M280 P3 S90 I1

