; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v2.0.4 on Thu Sep 26 2019 10:50:21 GMT+0200 (Central European Summer Time)

