; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v2.0.4 on Thu Sep 26 2019 10:50:21 GMT+0200 (Central European Summer Time)
; Wait for set temperatures to be reached
M116 P0

