; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v2 on Fri May 17 2019 17:30:33 GMT+0200 (hora de verano de Europa central)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


