; deployprobe.g
; called to deploy a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v2.1.8 on Sun Mar 08 2020 15:25:23 GMT+0100 (hora estándar de Europa central)
M280 P0 S10 ; deploy BLTouch

