; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v2.1.8 on Sun Mar 08 2020 15:25:31 GMT+0100 (hora estándar de Europa central)
; Wait for set temperatures to be reached
M116 P0

